/**
 * The rubric: what makes a prompt good, per input type.
 *
 * The item list is a direct reading of Anthropic's Claude prompting best
 * practices
 * (https://platform.claude.com/docs/en/build-with-claude/prompt-engineering/claude-prompting-best-practices):
 * be clear and direct (goal), add context, use examples, structure the output,
 * state constraints. TypeSafe's jev only returns probabilities, never prose, so
 * every hint is selected here in code instead of generated by the model.
 *
 * Two deliberate language choices:
 *  - `instructions` and `criteria` are English. Jev's primary training language
 *    is English, so the questions stay English even when the prompt is not.
 *  - Hint text is Japanese, because that is what the user reads.
 */

/** Question types accepted by POST /v1/systemone. */
export type Question =
  | { type: "noul"; instructions: string; criteria?: { true: string; false: string } }
  | { type: "choice"; instructions: string; criteria: Record<string, string> }
  | { type: "score"; instructions: string; criteria: string[] };

export type InputType = "question" | "task" | "analysis" | "creative" | "chitchat";

export interface ChecklistItem {
  /** Short Japanese label shown in the hint list. */
  label: string;
  /** The Noul instruction asked of jev. */
  ask: string;
  /** The Japanese hint shown when the item is missing. */
  hint: string;
}

export const INPUT_TYPES: Record<InputType, string> = {
  question: "The user asks for information or an explanation.",
  task: "The user asks for something to be created, changed, or executed.",
  analysis: "The user asks for existing material to be evaluated, compared, or diagnosed.",
  creative: "The user asks for prose, ideas, or other content to be written or generated.",
  chitchat: "Greeting, thanks, acknowledgement, or a short procedural reply with no real request.",
};

export const TYPE_LABELS: Record<InputType, string> = {
  question: "質問",
  task: "タスク依頼",
  analysis: "分析",
  creative: "創作",
  chitchat: "雑談",
};

/**
 * One entry per Noul question. The question id sent to jev is `has_<id>`.
 *
 * Noul answers are the probability that the item is present, so the same answer
 * is both the "is it there" bit and a rank of how barely-missing it is.
 */
export const ITEMS: Record<string, ChecklistItem> = {
  goal: {
    label: "目的・ゴール",
    ask: "Does `request` state what the user wants to achieve or obtain?",
    hint: "達成したいことを1文で書く（例: 「〜を〜の状態にしたい」）。",
  },
  context: {
    label: "背景・前提",
    ask: "Does `request` give the background, the situation, or the reason it is being asked?",
    hint: "背景・前提・なぜそれを聞きたいのかを添える。",
  },
  constraints: {
    label: "制約",
    ask: "Does `request` state constraints it must respect, such as tools, language, scope, deadline, or things to avoid?",
    hint: "守るべき条件を書く（言語・依存・対象範囲・締切・禁止事項）。",
  },
  output_format: {
    label: "出力形式",
    ask: "Does `request` specify the desired output format, structure, or length?",
    hint: "欲しい形式・長さ・構成を指定する（箇条書き / 表 / コード / 〜字以内）。",
  },
  success_criteria: {
    label: "完了条件",
    ask: "Does `request` state how the result will be judged or verified?",
    hint: "何をもって完了とするか、確認方法を書く（テスト・受け入れ条件）。",
  },
  examples: {
    label: "例",
    ask: "Does `request` include an example of the desired input or output?",
    hint: "期待する出力の例を1〜2個添える（few-shot）。",
  },
  audience: {
    label: "読み手",
    ask: "Does `request` name who the result is for?",
    hint: "誰が読む・使うかを書く（専門家 / 初心者 / 経営層）。",
  },
  tone: {
    label: "トーン・文体",
    ask: "Does `request` specify the tone or writing style?",
    hint: "文体・トーンを指定する（です・ます / 断定 / カジュアル）。",
  },
  eval_criteria: {
    label: "評価軸",
    ask: "Does `request` name the axes to evaluate or compare on?",
    hint: "何の軸で評価・比較するかを列挙する。",
  },
  data_source: {
    label: "対象データ",
    ask: "Does `request` name the material to analyze and where it lives?",
    hint: "対象の資料・ファイル・範囲を指定する。",
  },
  prior_attempts: {
    label: "試したこと",
    ask: "Does `request` describe what has already been tried and what happened?",
    hint: "すでに試したことと、その結果を書く。",
  },
  decision_use: {
    label: "用途",
    ask: "Does `request` say what decision the answer will inform?",
    hint: "得た答えを何の判断に使うかを書く。",
  },
};

/** Items expected for each input type, in priority order. */
export const REQUIRED: Record<InputType, readonly string[]> = {
  question: ["goal", "context", "prior_attempts", "decision_use"],
  task: ["goal", "context", "constraints", "output_format", "success_criteria"],
  analysis: ["goal", "context", "data_source", "eval_criteria", "output_format"],
  creative: ["goal", "context", "audience", "tone", "examples"],
  chitchat: [],
};

/**
 * Used when `input_type` comes back with low confidence. Judging against the
 * wrong type's checklist would invent hints, so fall back to what every request
 * needs.
 */
export const FALLBACK_ITEMS: readonly string[] = ["goal", "context"];

export const CLARITY_LEVELS = [
  "Ambiguous; the reader cannot tell the actual ask without guessing",
  "Mostly clear, but a second reading is still plausible",
  "Unambiguous; a reader with no extra context knows exactly what is asked",
];

export const SPECIFICITY_LEVELS = [
  "Only abstract generalities; no concrete nouns, files, or numbers",
  "Some concrete detail, but the key specifics are still left out",
  "Concrete and detailed; names the actual files, values, or steps involved",
];

/**
 * Every question for every type in one request. jev evaluates them in parallel,
 * so asking speculatively is cheaper than a second round trip; `assess()` reads
 * only the ones the classified type needs.
 */
export function buildQuestions(): Record<string, Question> {
  const questions: Record<string, Question> = {
    input_type: {
      type: "choice",
      instructions: "What kind of request is this?",
      criteria: INPUT_TYPES,
    },
    clarity: {
      type: "score",
      instructions: "How clear is `request` to a reader with no extra context?",
      criteria: CLARITY_LEVELS,
    },
    specificity: {
      type: "score",
      instructions: "How specific and concrete is `request`?",
      criteria: SPECIFICITY_LEVELS,
    },
  };
  for (const [id, item] of Object.entries(ITEMS)) {
    questions[`has_${id}`] = {
      type: "noul",
      instructions: item.ask,
      criteria: {
        true: "Stated, or so clearly implied that no reader would ask for it",
        false: "Not stated in `request`",
      },
    };
  }
  return questions;
}
