/**
 * The rubric: what makes a prompt good, per input type.
 *
 * The item list is a direct reading of Anthropic's Claude prompting best
 * practices
 * (https://platform.claude.com/docs/en/build-with-claude/prompt-engineering/claude-prompting-best-practices):
 * be clear and direct (goal), add context, use examples, structure the output,
 * state constraints. TypeSafe's jev only returns probabilities, never prose, so
 * every hint is selected here in code instead of generated by the model.
 *
 * Two deliberate language choices:
 *  - `instructions` and `criteria` are English. Jev's primary training language
 *    is English, so the questions stay English even when the prompt is not.
 *  - `hint` is English, because the agent reads it. `label` stays Japanese,
 *    because the user reads the gap list in the footer.
 */

/** Question types accepted by POST /v1/systemone. */
export type Question =
  | { type: "noul"; instructions: string; criteria?: { true: string; false: string } }
  | { type: "choice"; instructions: string; criteria: Record<string, string> }
  | { type: "score"; instructions: string; criteria: string[] };

export type InputType = "question" | "task" | "analysis" | "creative" | "chitchat";

export interface ChecklistItem {
  /** Short Japanese label for the footer gap list, which the user reads. */
  label: string;
  /** The Noul instruction asked of jev. */
  ask: string;
  /** English instruction for the agent, sent when the item is missing. */
  hint: string;
}

export const INPUT_TYPES: Record<InputType, string> = {
  question: "The user asks for information or an explanation.",
  task: "The user asks for something to be created, changed, or executed.",
  analysis: "The user asks for existing material to be evaluated, compared, or diagnosed.",
  creative: "The user asks for prose, ideas, or other content to be written or generated.",
  chitchat: "Greeting, thanks, acknowledgement, or a short procedural reply with no real request.",
};

export const TYPE_LABELS: Record<InputType, string> = {
  question: "質問",
  task: "タスク依頼",
  analysis: "分析",
  creative: "創作",
  chitchat: "雑談",
};

/**
 * One entry per Noul question. The question id sent to jev is `has_<id>`.
 *
 * Noul answers are the probability that the item is present, so the same answer
 * is both the "is it there" bit and a rank of how barely-missing it is.
 */
export const ITEMS: Record<string, ChecklistItem> = {
  goal: {
    label: "目的・ゴール",
    ask: "Does `request` state what the user wants to achieve or obtain?",
    hint: "State what the reader should achieve, in one sentence.",
  },
  context: {
    label: "背景・前提",
    ask: "Does `request` give the background, the situation, or the reason it is being asked?",
    hint: "Add the background, the situation, and the reason this matters.",
  },
  constraints: {
    label: "制約",
    ask: "Does `request` state constraints it must respect, such as tools, language, scope, deadline, or things to avoid?",
    hint: "State the constraints: language, dependencies, scope, deadline, off-limits areas.",
  },
  output_format: {
    label: "出力形式",
    ask: "Does `request` specify the desired output format, structure, or length?",
    hint: "Specify the output format, structure, and length (prose, bullets, table, code, size cap).",
  },
  success_criteria: {
    label: "完了条件",
    ask: "Does `request` state how the result will be judged or verified?",
    hint: "State how the result gets judged or verified (tests, acceptance criteria).",
  },
  examples: {
    label: "例",
    ask: "Does `request` include an example of the desired input or output?",
    hint: "Add one or two examples of the desired input or output.",
  },
  audience: {
    label: "読み手",
    ask: "Does `request` name who the result is for?",
    hint: "Name the audience (expert, beginner, executive).",
  },
  tone: {
    label: "トーン・文体",
    ask: "Does `request` specify the tone or writing style?",
    hint: "Specify the tone and the writing style.",
  },
  eval_criteria: {
    label: "評価軸",
    ask: "Does `request` name the axes to evaluate or compare on?",
    hint: "List the axes to evaluate or compare on.",
  },
  data_source: {
    label: "対象データ",
    ask: "Does `request` name the material to analyze and where it lives?",
    hint: "Name the material to analyze and where it lives.",
  },
  prior_attempts: {
    label: "試したこと",
    ask: "Does `request` describe what has already been tried and what happened?",
    hint: "Describe what has already been tried and what happened.",
  },
  decision_use: {
    label: "用途",
    ask: "Does `request` say what decision the answer will inform?",
    hint: "State which decision the answer informs.",
  },
};

/** Items expected for each input type, in priority order. */
export const REQUIRED: Record<InputType, readonly string[]> = {
  question: ["goal", "context", "prior_attempts", "decision_use"],
  task: ["goal", "context", "constraints", "output_format", "success_criteria"],
  analysis: ["goal", "context", "data_source", "eval_criteria", "output_format"],
  creative: ["goal", "context", "audience", "tone", "examples"],
  chitchat: [],
};

/**
 * Used when `input_type` comes back with low confidence. Judging against the
 * wrong type's checklist would invent hints, so fall back to what every request
 * needs.
 */
export const FALLBACK_ITEMS: readonly string[] = ["goal", "context"];

/**
 * Every question for every type in one request. jev evaluates them in parallel,
 * so asking speculatively is cheaper than a second round trip; `assess()` reads
 * only the ones the classified type needs.
 *
 * One Choice plus one Noul per item. A Score question would carry no weight:
 * the score is a deduction over confirmed gaps.
 */
export function buildQuestions(): Record<string, Question> {
  const questions: Record<string, Question> = {
    input_type: {
      type: "choice",
      instructions: "What kind of request is this?",
      criteria: INPUT_TYPES,
    },
  };
  for (const [id, item] of Object.entries(ITEMS)) {
    questions[`has_${id}`] = {
      type: "noul",
      instructions: item.ask,
      criteria: {
        true: "Stated, or so clearly implied that no reader would ask for it",
        false: "Not stated in `request`",
      },
    };
  }
  return questions;
}
